-- ============================================================
-- Alsace Hideaways – MySQL Schema
-- Run this against your MySQL 8.0+ (or MariaDB 10.2+) database.
--
-- This replaces the previous PostgreSQL/Supabase schema. Notable
-- translations from the Postgres version:
--   - SERIAL / BIGSERIAL        -> INT/BIGINT AUTO_INCREMENT
--   - UUID DEFAULT gen_random_uuid() -> CHAR(36), generated by the PHP
--     app (see App\Helpers\Uuid) before INSERT, since MySQL has no
--     built-in equivalent column default
--   - TIMESTAMPTZ / NOW()       -> TIMESTAMP / CURRENT_TIMESTAMP
--   - TEXT UNIQUE / TEXT REFERENCES -> VARCHAR(255) (MySQL needs a
--     bounded key length for unique/foreign keys)
--   - date1 - date2 in a CHECK  -> DATEDIFF(date1, date2)
--   - ON CONFLICT ... DO NOTHING -> INSERT IGNORE
-- ============================================================

SET NAMES utf8mb4;

-- 1. PROPERTIES (reference list)
CREATE TABLE IF NOT EXISTS properties (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(255) NOT NULL UNIQUE,
  description   TEXT,
  max_guests    INT NOT NULL DEFAULT 12,
  bedrooms      INT,
  beds          INT,
  bathrooms     INT,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO properties (name, description, max_guests, bedrooms, beds, bathrooms) VALUES
  ('Shelter A',             'Premium 3-bedroom rental unit in Griesheim-près-Molsheim, ideal for extended stays. 8 guests max.',                  8, 3, 7, 1),
  ('Shelter B',             'The Agaves Refuge - Charming 3-bedroom cottage in Griesheim-près-Molsheim with fenced garden. 8 guests max.',     8, 3, 7, 1),
  ('La Maison Modern',      'Beautiful modern 5-bedroom house with underfloor heating in Griesheim-près-Molsheim. 15 guests max.',           15, 5, 13, 2),
  ('La Refuge de la Martre','Charming renovated farmhouse with 6 bedrooms in Griesheim-près-Molsheim. 15 guests max.',                      15, 6, 14, 2);


-- 2. PROPERTY PRICING (base weekday/weekend rates per property)
CREATE TABLE IF NOT EXISTS property_pricing (
    property_id INT PRIMARY KEY,

    weekday_price DECIMAL(10,2) NOT NULL
        CHECK (weekday_price > 0),

    weekend_price DECIMAL(10,2) NOT NULL
        CHECK (weekend_price > 0),

    extra_person_fee DECIMAL(10,2) NOT NULL DEFAULT 0
        CHECK (extra_person_fee >= 0),

    cleaning_fee DECIMAL(10,2) NOT NULL DEFAULT 40
        CHECK (cleaning_fee >= 0),

    linen_fee DECIMAL(10,2) NOT NULL DEFAULT 12
        CHECK (linen_fee >= 0),

    -- Security deposit (caution) amount, separate from and much smaller
    -- than the rental total. Charged via a Swikly Deposit request once an
    -- admin approves the reservation, not collected at booking time.
    deposit_amount DECIMAL(10,2) NOT NULL DEFAULT 0
        CHECK (deposit_amount >= 0),

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_property_pricing_property
        FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- 3. RESERVATIONS
-- id is a UUID generated by the PHP app (App\Helpers\Uuid::v4()), not the database.
--
-- property_id was added here during the MySQL port: AvailabilityController's
-- check()/checkBatch() overlap queries filter reservations by property_id,
-- but that column never existed in the original Postgres schema (only
-- property_name did) — those two endpoints would 500 against the documented
-- schema. ReservationsController::create() now resolves and stores both.
CREATE TABLE IF NOT EXISTS reservations (
  id             CHAR(36) PRIMARY KEY,
  property_name  VARCHAR(255) NOT NULL,
  property_id    INT NULL,
  guests         INT NOT NULL CHECK (guests >= 1),
  checkin        DATE NOT NULL,
  checkout       DATE NOT NULL,
  name           VARCHAR(255) NOT NULL,
  phone          VARCHAR(50) NOT NULL,
  email          VARCHAR(255) NOT NULL,
  total_price    DECIMAL(10,2) NOT NULL,
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending'
                   CHECK (payment_status IN ('pending','paid','failed')),
  confirmed      BOOLEAN NOT NULL DEFAULT FALSE,
  cancelled      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- Set when an admin approves the reservation and a Swikly Deposit request
  -- is created for it — lets the dashboard re-show/re-send the same link.
  swikly_request_id VARCHAR(255) NULL,
  swikly_link        VARCHAR(500) NULL,

  CONSTRAINT checkout_after_checkin CHECK (checkout > checkin),
  CONSTRAINT fk_reservations_property_name
      FOREIGN KEY (property_name) REFERENCES properties(name),
  CONSTRAINT fk_reservations_property_id
      FOREIGN KEY (property_id) REFERENCES properties(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_reservations_property_dates
  ON reservations (property_name, checkin, checkout);
CREATE INDEX idx_reservations_property_id_dates
  ON reservations (property_id, checkin, checkout);


-- 4. BLOCKED DATES
CREATE TABLE IF NOT EXISTS blocked_dates (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  property_name VARCHAR(255) NOT NULL,
  blocked_date  DATE NOT NULL,
  reason        VARCHAR(20) NOT NULL DEFAULT 'manual_block'
                  CHECK (reason IN ('maintenance','manual_block')),
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_blocked_dates_property_name
      FOREIGN KEY (property_name) REFERENCES properties(name),
  UNIQUE (property_name, blocked_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_blocked_dates_property
  ON blocked_dates (property_name, blocked_date);


-- 5. PRICING OVERRIDES (date-specific price overrides)
CREATE TABLE IF NOT EXISTS pricing_overrides (
    property_id INT NOT NULL,

    override_date DATE NOT NULL,

    price DECIMAL(10,2) NOT NULL
        CHECK (price > 0),

    reason VARCHAR(255),

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (property_id, override_date),
    CONSTRAINT fk_pricing_overrides_property
        FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_pricing_overrides_property
  ON pricing_overrides (property_id, override_date);


-- 6. ADMIN USERS (username/password login for the admin panel)
-- id is a UUID generated by the PHP app (App\Helpers\Uuid::v4()), not the database.
CREATE TABLE IF NOT EXISTS admin_users (
  id            CHAR(36) PRIMARY KEY,
  username      VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default admin user (id generated below — UUID() is MySQL/MariaDB's
-- random-string function, used here only as a one-off seed value).
-- Username: admin
-- Password: admin123 (bcrypt hash - change this in production!)
-- NOTE: the hash carried over from the old Postgres schema.sql did not
-- actually correspond to "admin123" (verified with password_verify() —
-- pre-existing bug, not introduced by this MySQL port). Regenerated below.
INSERT IGNORE INTO admin_users (id, username, password_hash) VALUES
  (UUID(), 'admin', '$2y$10$WwLjikcS1RNJDtosp2AnuuKFG12acow6SupMpOAZHraCZ8ncUkl6u');


-- 7. PROPERTY BLOCKS (date blocking for manual, airbnb, booking, maintenance)
CREATE TABLE IF NOT EXISTS property_blocks (
  id               BIGINT AUTO_INCREMENT PRIMARY KEY,
  property_id      INT NOT NULL,
  start_date       DATE NOT NULL,
  end_date         DATE NOT NULL,
  block_type       VARCHAR(50) NOT NULL
                   CHECK (block_type IN ('manual', 'airbnb', 'booking', 'maintenance')),
  source_reference VARCHAR(255),
  notes            TEXT,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_property_blocks_property
      FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  CONSTRAINT end_after_start CHECK (end_date >= start_date),
  CONSTRAINT valid_block_range CHECK (DATEDIFF(end_date, start_date) <= 730) -- max 2 years
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_property_blocks_property_dates
  ON property_blocks (property_id, start_date, end_date);
CREATE INDEX idx_property_blocks_type
  ON property_blocks (property_id, block_type);


-- 8. PROPERTY ICAL SOURCES (iCal feed URLs for syncing)
CREATE TABLE IF NOT EXISTS property_ical_sources (
  id               BIGINT AUTO_INCREMENT PRIMARY KEY,
  property_id      INT NOT NULL,
  provider         VARCHAR(50) NOT NULL
                   CHECK (provider IN ('airbnb', 'booking', 'vrbo')),
  ical_url         TEXT NOT NULL,
  last_sync_at     TIMESTAMP NULL,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_property_ical_sources_property
      FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  CONSTRAINT unique_provider_per_property UNIQUE (property_id, provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_property_ical_sources_property
  ON property_ical_sources (property_id);


-- 9. IMPORTED CALENDAR EVENTS (events parsed from synced iCal feeds)
CREATE TABLE IF NOT EXISTS imported_calendar_events (
  id               BIGINT AUTO_INCREMENT PRIMARY KEY,
  property_id      INT NOT NULL,
  external_uid     VARCHAR(255) NOT NULL,
  source_provider  VARCHAR(50) NOT NULL
                   CHECK (source_provider IN ('airbnb', 'booking', 'vrbo')),
  start_date       DATE NOT NULL,
  end_date         DATE NOT NULL,
  summary          TEXT,
  last_seen_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_imported_calendar_events_property
      FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  CONSTRAINT end_after_start CHECK (end_date >= start_date),
  CONSTRAINT unique_external_event UNIQUE (external_uid, property_id, source_provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_imported_calendar_events_property_dates
  ON imported_calendar_events (property_id, start_date, end_date);
CREATE INDEX idx_imported_calendar_events_provider
  ON imported_calendar_events (property_id, source_provider);


-- 10. PRICING TIERS (seasonal/single-day/weekend/yearly overrides by property
-- name — queried by PricingController, though not yet wired into routes.php)
--
-- The Postgres version upserted against two different conflict targets
-- depending on tier_type: (property_name, tier_type, specific_date) for
-- 'single_day' rows, and (property_name, tier_type) for 'weekend'/'yearly'
-- rows (achievable there via two partial unique indexes). MySQL has no
-- partial/filtered unique index, so a generated column collapses both
-- rules into one real unique key: specific_date is only meaningful for
-- 'single_day', so non-single_day rows are normalized to a constant
-- sentinel date, making (property_name, tier_type, specific_date_key)
-- enforce "one row per date" for single_day and "one row per type" for
-- the other two.
CREATE TABLE IF NOT EXISTS pricing_tiers (
  id                BIGINT AUTO_INCREMENT PRIMARY KEY,
  property_name     VARCHAR(255) NOT NULL,
  tier_type         VARCHAR(20) NOT NULL
                    CHECK (tier_type IN ('single_day', 'weekend', 'yearly')),
  specific_date     DATE NULL,
  base_price        DECIMAL(10,2) NOT NULL,
  extra_person_fee  DECIMAL(10,2),
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  specific_date_key DATE GENERATED ALWAYS AS
                    (COALESCE(specific_date, '0001-01-01')) STORED,

  CONSTRAINT fk_pricing_tiers_property_name
      FOREIGN KEY (property_name) REFERENCES properties(name),
  CONSTRAINT unique_pricing_tier UNIQUE (property_name, tier_type, specific_date_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
